[package]
name = "rust_boy"
version = "0.1.0"
authors = ["Michael Rivnak <mrivnak86@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
